/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import videoField from "@sklinet/strapi-plugin-video-field/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiPluginCkeditor5 from "strapi-plugin-ckeditor5/strapi-admin";
import navigation from "strapi-plugin-navigation/strapi-admin";
import netlifyDeployments from "strapi-plugin-netlify-deployments/strapi-admin";
import restCache from "strapi-plugin-rest-cache/strapi-admin";
import sitemap from "strapi-plugin-sitemap/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "video-field": videoField,
    graphql: graphql,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "strapi-plugin-ckeditor5": strapiPluginCkeditor5,
    navigation: navigation,
    "netlify-deployments": netlifyDeployments,
    "rest-cache": restCache,
    sitemap: sitemap,
  },
});
